spring:
  application:
    name: gateway-service

  docker:
    compose:
      enabled: false

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: scheduler
              uri: lb://scheduler-service
              predicates:
                - Path=/scheduler/**
            - id: executor
              uri: lb://executor-service
              predicates:
                - Path=/executor/**
            - id: telemetry
              uri: lb://telemetry-service
              predicates:
                - Path=/telemetry/**

server:
  port: 8080
  # address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
